"""The transfer, argued the way a manager would argue it.

The player write-ups answer "why should this player be in my team". The
transfer section answered something narrower and much less useful: why
the incoming player is good. That is not the decision. The decision is
whether this is the best use of a transfer, which is a question about the
whole squad, the money, the hit, the alternatives, and next week.

So every section here is a named judgement rather than a paragraph of
supporting sentences:

    WHY THIS MOVE        the overall logic, in a manager's terms
    THE CASE FOR         the positive argument, from evidence
    THE CASE AGAINST     always populated; a move with no downside has
                         not been thought about
    WHY THIS PLAYER OUT  measured against the next realistic sales
    WHY THIS PLAYER IN   measured against the realistic alternatives
    WHY NOW              or an admission that there is no urgency
    WHY NOT ROLL         the flexibility given up, priced
    3-5 GAMEWEEK PLAN    where this leaves the squad, and what it forces
    VERDICT              a label that matches the maths
    CONFIDENCE           earned, and never High on uncertain minutes

Two rules shape the whole module. A HIT IS FOUR REAL POINTS and appears
in the headline arithmetic, not as an annotation. And EVIDENCE IS NOT AN
ARGUMENT until it has been interpreted — every claim here is written as
what was observed, what it means, and what it does to the decision.

Nothing is fetched and nothing is generated by a model: this reads the
plans the engine already costed and the status pass already checked.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from fpl_assistant.analysis import strategy as st

# A move needs a reason to happen THIS week rather than next. Below this
# five-gameweek edge, waiting costs almost nothing and buys information.
URGENCY_EDGE = 2.0
# Inside this, two options are the same option.
LEVEL_PEGGING = 1.0


@dataclass
class Side:
    """One end of a swap, with everything the argument needs about him."""

    name: str = ""
    club: str = ""
    position: str = ""
    price: float = 0.0
    outlook: str = ""
    minutes_label: str = ""
    confidence: str = ""
    starts: int = 0
    team_games: int = 0
    new_club: str = ""
    injury: str = ""
    set_pieces: bool = False
    penalties: bool = False
    sell_urgency: float = 0.0
    hold_strength: float = 0.0
    five_gw: float = 0.0
    fixtures: list = field(default_factory=list)   # [(label, difficulty)]
    evidence: list = field(default_factory=list)

    @property
    def secure(self) -> bool:
        return self.outlook in ("Very likely to start", "Likely to start")

    def run(self, weeks: int) -> float:
        scores = [difficulty for _, difficulty in self.fixtures[:weeks]]
        return sum(scores) / len(scores) if scores else 3.0

    def labels(self, weeks: int = 4) -> str:
        known = [label for label, _ in self.fixtures[:weeks]
                 if label and label.strip("— ")]
        return " → ".join(known) if known else "no fixture list available"


@dataclass
class TransferBriefInputs:
    """Everything one transfer argument is allowed to use."""

    plan: "st.Plan" = None
    sides: list = field(default_factory=list)      # [(out Side, in Side), ...]
    roll_net: float = 0.0
    margin: float = 0.0
    close_call: bool = False
    free_transfers: int = 1
    bank_before: float = 0.0
    # The next realistic sales, so "why him" is a comparison and not an
    # assertion: [(name, sell_urgency, band, outlook)]
    other_sales: list = field(default_factory=list)
    # The other targets the engine costed for the same outgoing player:
    # [(name, five_gw_delta, why_not)]
    other_targets: list = field(default_factory=list)
    gameweek: int = 0

    @property
    def acting(self) -> bool:
        return bool(self.plan and self.plan.moves)


@dataclass
class TransferBrief:
    """One decision, in the order a manager reads it."""

    label: str = ""
    why_move: str = ""
    case_for: str = ""
    case_against: str = ""
    why_out: str = ""
    why_in: str = ""
    why_now: str = ""
    why_not_roll: str = ""
    horizon: str = ""
    verdict: str = ""
    verdict_label: str = ""
    confidence: str = "Medium"
    arithmetic: str = ""
    evidence: list = field(default_factory=list)
    trust: list = field(default_factory=list)

    @property
    def trusted(self) -> bool:
        return all(passed for _, passed, _ in self.trust)

    def as_dict(self) -> dict:
        return {"label": self.label, "why_move": self.why_move,
                "case_for": self.case_for, "case_against": self.case_against,
                "why_out": self.why_out, "why_in": self.why_in,
                "why_now": self.why_now, "why_not_roll": self.why_not_roll,
                "horizon": self.horizon, "verdict": self.verdict,
                "verdict_label": self.verdict_label,
                "confidence": self.confidence, "arithmetic": self.arithmetic,
                "evidence": self.evidence[:8],
                "trust": [{"question": q, "passed": p, "detail": d}
                          for q, p, d in self.trust],
                "trusted": self.trusted}


# --- the verdicts a manager can act on -----------------------------------

MAKE_THE_MOVE = "MAKE THE MOVE"
ROLL = "ROLL"
HOLD_A_WEEK = "HOLD OFF FOR ONE WEEK"
WATCHLIST = "WATCHLIST — REASSESS NEXT GW"
CONDITIONAL = "ONLY MAKE IF THE MINUTES ARE CONFIRMED"
NOT_WORTH_A_HIT = "NOT WORTH A -4"


# --- the arithmetic, stated before any prose -----------------------------

def arithmetic(inputs: TransferBriefInputs) -> str:
    """The money and the hit, in one line, before anything is argued.

    A HIT IS FOUR REAL POINTS. Burying it inside a weighted score is how
    a move that loses points can be presented as one that gains them, so
    the gross figure, the hit and the net all appear together and the net
    is the one the verdict has to match.
    """
    plan = inputs.plan
    if not plan or not plan.moves:
        return (f"No transfer. {inputs.free_transfers} free transfer becomes "
                f"{min(5, inputs.free_transfers + 1)} next week, "
                f"£{inputs.bank_before:.1f}m stays in the bank.")
    parts = [f"Gross {plan.gross_5gw:+.1f} over five gameweeks"]
    if plan.hit:
        parts.append(
            f"a {plan.hit:.0f}-point hit for {plan.paid_transfers} transfer"
            f"{'s' if plan.paid_transfers != 1 else ''} beyond the free one")
        parts.append(f"net {plan.net_5gw:+.1f}")
    else:
        parts.append("no hit, this is within your free transfers")
        parts.append(f"net {plan.net_5gw:+.1f} after the flexibility given up")
    if plan.affordable:
        parts.append(
            f"£{plan.bank_before:.1f}m → £{plan.bank_after:.1f}m in the bank")
    else:
        parts.append(
            f"UNAFFORDABLE — it needs £{-plan.bank_after:.1f}m more than the "
            f"squad can raise")
    parts.append(f"{plan.free_transfers_after} free transfer"
                 f"{'s' if plan.free_transfers_after != 1 else ''} next week")
    return ". ".join(part[0].upper() + part[1:] for part in parts) + "."


# --- 1. why this move ----------------------------------------------------

def why_move(inputs: TransferBriefInputs, label: str = "") -> str:
    """The overall logic, in the terms a manager would use.

    Answers "why is this the best use of my transfer", not "why is the
    incoming player good" — which is the substitution the old section
    made, and the reason it read like a scouting note rather than a
    decision.
    """
    plan = inputs.plan
    if not inputs.acting:
        return roll_logic(inputs)

    out, into = inputs.sides[0]
    problem = _problem_phrase(out)
    lines = [f"This move {problem}."]

    if len(plan.moves) > 1:
        lines.append(package_logic(inputs))
    else:
        lines.append(
            f"{into.name} offers {_offer_phrase(out, into)}, and the swap "
            f"{_cost_phrase(plan)}.")

    if plan.hit:
        lines.append(
            f"Because it costs {plan.hit:.0f} points, the gross "
            f"{plan.gross_5gw:+.1f} has to clear that before any of it "
            f"counts — after the hit the edge is {plan.net_5gw:+.1f}.")
    elif label and label != MAKE_THE_MOVE:
        # The opening section cannot advocate for a decision the verdict
        # declines. It sets out the logic; the verdict says what happened
        # to it.
        lines.append(
            "It uses only the free transfer, so the arithmetic is not what "
            "stops it — see the verdict for what does.")
    else:
        lines.append(
            f"It uses only the free transfer and leaves the squad legal and "
            f"balanced, which is what makes it a better use of the week than "
            f"selling a settled asset somewhere else.")
    return " ".join(lines)


def _problem_phrase(out: Side) -> str:
    if out.injury or out.outlook == "Out":
        return f"removes a player who is not going to be available"
    if not out.secure:
        return (f"fixes a genuine weak point rather than chasing a projection: "
                f"{out.name} is {out.outlook.lower()} at {out.minutes_label}")
    if out.sell_urgency >= 45:
        return (f"addresses the squad's most pressing problem — {out.name} at "
                f"{out.sell_urgency:.0f}/100 for sell urgency")
    return (f"upgrades a slot that is not broken, which is a higher bar and "
            f"has to be justified by the size of the gain rather than by need")


def _offer_phrase(out: Side, into: Side) -> str:
    parts = []
    if into.secure and not out.secure:
        parts.append("a more secure starting place")
    if into.run(4) + 0.4 < out.run(4):
        parts.append("a kinder run of fixtures")
    if into.penalties and not out.penalties:
        parts.append("penalty duty")
    elif into.set_pieces and not out.set_pieces:
        parts.append("set-piece responsibility")
    if not parts:
        parts.append(f"{into.five_gw - out.five_gw:+.1f} points over five "
                     f"gameweeks on the model's reading")
    if len(parts) == 1:
        return parts[0]
    return ", ".join(parts[:-1]) + f" and {parts[-1]}"


def _cost_phrase(plan) -> str:
    if plan.bank_after > plan.bank_before + 0.05:
        return (f"releases £{plan.bank_after - plan.bank_before:.1f}m rather "
                f"than spending")
    if plan.bank_after < plan.bank_before - 0.05:
        return (f"spends £{plan.bank_before - plan.bank_after:.1f}m of the "
                f"bank")
    return "is close to money-neutral"


def roll_logic(inputs: TransferBriefInputs) -> str:
    """Why doing nothing is the move, when it is."""
    return (
        "The best use of this week's transfer is not to spend it. Nothing in "
        "the squad has deteriorated enough to need fixing, and no available "
        "move clears the value of carrying a second free transfer into next "
        "week — which is worth real points as the option to react to news "
        "nobody has published yet.")


# --- 2. the case for -----------------------------------------------------

def case_for(inputs: TransferBriefInputs) -> str:
    """The positive argument, built from evidence rather than adjectives.

    Each claim is written as what was observed, what it means, and what
    it does to the decision — because "he has started every game" is a
    fact, and "that raises the bar for selling him" is an argument.
    """
    if not inputs.acting:
        return (
            "Rolling keeps two free transfers for next week, which is the "
            "only position from which a two-move package can be made without "
            "a hit. That flexibility is worth more than any single swing "
            "available this week.")

    lines = []
    for out, into in inputs.sides:
        prefix = f"{into.name} " if len(inputs.sides) > 1 else ""
        if into.secure:
            lines.append(
                f"{into.name} is {into.outlook.lower()} at "
                f"{into.minutes_label}, so the projection behind him is one he "
                f"is actually on the pitch to deliver.")
        if into.penalties:
            lines.append(
                f"{prefix or 'He '}takes the penalties, which is the largest "
                f"single swing available at his price and the kind of edge "
                f"that does not depend on form.".replace("  ", " "))
        elif into.set_pieces:
            lines.append(
                f"{prefix or 'He '}is on set pieces, which adds returns the "
                f"open-play numbers do not capture.")
        if into.run(4) + 0.4 < out.run(4):
            lines.append(
                f"{into.name}'s next four ({into.labels()}) grade easier than "
                f"the run being given up ({out.labels()}), so the gain is not "
                f"a one-week trick.")

    supporting = [reason.text for move in inputs.plan.moves
                  for reason in st.supports_buying(move)][:2]
    for text in supporting:
        lines.append(f"Published this week: {text.rstrip('.')}. That is "
                     f"current reporting about him rather than a model output.")

    if inputs.plan.bank_after > inputs.plan.bank_before + 0.3:
        lines.append(
            f"It also releases £{inputs.plan.bank_after - inputs.plan.bank_before:.1f}m, "
            f"which is what makes a bigger move possible later.")

    if not lines:
        lines.append(
            f"The case rests on the projection alone: {into.name} models "
            f"{into.five_gw - out.five_gw:+.1f} better over five gameweeks. "
            f"That is a claim, not evidence, and it is why the confidence "
            f"below is not higher.")
    return " ".join(lines)


# --- 3. the case against -------------------------------------------------

def case_against(inputs: TransferBriefInputs) -> str:
    """The argument against the recommendation, always populated.

    A move with no identified downside has not been thought about. Where
    the engine genuinely cannot find one, the honest answer is that the
    case rests on a projection — which is itself the strongest objection
    available.
    """
    if not inputs.acting:
        best = _best_rejected(inputs)
        if best:
            return (
                f"The argument against rolling is {best}. If that reading is "
                f"right, a week of it is lost — but the evidence for it is "
                f"not there yet, and acting on a projection alone is what "
                f"this engine is built not to do.")
        return ("The argument against rolling is that a free transfer kept "
                "too long is a free transfer wasted. It is worth acting on "
                "the moment anything is published against a squad member.")

    plan, (out, into) = inputs.plan, inputs.sides[0]
    doubts = []

    if not plan.affordable:
        doubts.append(
            f"it cannot be afforded — £{plan.bank_after:.1f}m in the bank "
            f"afterwards, so the move does not exist as described")

    if out.secure and out.sell_urgency < 30:
        doubts.append(
            f"the biggest downside is that {out.name} is not a problem — "
            f"{out.outlook.lower()} at {out.sell_urgency:.0f}/100 sell "
            f"urgency — so this is an upgrade, not a repair, and upgrades are "
            f"where transfers get wasted")
    if out.hold_strength >= 65:
        doubts.append(
            f"{out.name}'s hold strength is {out.hold_strength:.0f}, which "
            f"means a real chance of wanting him back at a higher price")
    if not into.secure:
        doubts.append(
            f"{into.name} is only {into.outlook.lower()} at "
            f"{into.minutes_label}, so the projection assumes minutes he has "
            f"not been confirmed to have")
    if into.new_club:
        doubts.append(
            f"{into.name} has just changed clubs, and a role that looks "
            f"settled for a fortnight can stop being settled")
    if plan.hit:
        doubts.append(
            f"the {plan.hit:.0f}-point hit is real and immediate, while the "
            f"gain is spread over five gameweeks and is a projection")
    if abs(plan.gross_5gw) < LEVEL_PEGGING:
        doubts.append(
            "the swing is inside the model's own margin of error, which makes "
            "this close to a sideways move")
    if into.run(2) + 0.5 < into.run(5):
        doubts.append(
            f"his run turns after the opening fixtures ({into.labels(5)}), so "
            f"this could need reversing inside a month")
    if inputs.close_call:
        doubts.append(
            "the margin over rolling is small enough that one piece of team "
            "news could flip it")
    if plan.bank_after < 0.2 and plan.bank_before >= 0.5:
        doubts.append(
            f"it leaves £{plan.bank_after:.1f}m in the bank, which removes the "
            f"room to react to anything that needs money next week")

    if not doubts:
        doubts.append(
            "nothing published this week argues against it, which is a "
            "thinner kind of comfort than it sounds — the case rests on the "
            "model's own numbers and would be stronger with a team sheet "
            "behind it")
    return _prose(doubts)


def _prose(parts: list) -> str:
    parts = [p.rstrip(".") for p in parts if p]
    if not parts:
        return ""
    lead = parts[0][0].upper() + parts[0][1:]
    if len(parts) == 1:
        return lead + "."
    rest = parts[1:3]
    if len(rest) == 1:
        return f"{lead}. On top of that, {rest[0]}."
    return f"{lead}. On top of that, {rest[0]}, and {rest[1]}."


def _best_rejected(inputs: TransferBriefInputs) -> str:
    for name, delta, why_not in inputs.other_targets[:1]:
        return (f"{name} models {delta:+.1f} better over five gameweeks")
    return ""


# --- 4. why THIS player out ----------------------------------------------

def why_out(inputs: TransferBriefInputs) -> str:
    """Why this owned player and not the next two.

    "Player B is better" is not an answer to "why sell player A". The
    comparison is against the other realistic sales, and if it cannot be
    made the move should not be recommended — which is what the trust
    test below checks.
    """
    if not inputs.acting:
        return ""
    sold = [out for out, _ in inputs.sides]
    lines = []
    for out in sold:
        lines.append(
            f"{out.name} is a sale because he is {out.outlook.lower()} at "
            f"{out.minutes_label}, on {out.sell_urgency:.0f}/100 for sell "
            f"urgency.")
    out = sold[0]
    names = {side.name for side in sold}
    pool = [row for row in inputs.other_sales if row[0] not in names]
    # Same position first: "he is a better sale than the backup
    # goalkeeper" is not an argument about a midfielder, and it appeared
    # twice in a row because the pool was never filtered.
    same = [row for row in pool if len(row) > 4 and row[4] == out.position]
    others = (same or pool)[:2]
    for row in others:
        name, urgency, band, outlook = row[:4]
        if max(urgency, out.sell_urgency) < 30:
            # Both are fine. Ranking noise as though it were a finding
            # ("scores higher at 16") reads as a problem where there is
            # none, and the honest answer is that neither is a sale.
            lines.append(
                f"Neither he nor {name} ({urgency:.0f}/100) is a squad "
                f"problem, so this is a choice between two players who are "
                f"both doing their job — which is the weakest ground a "
                f"transfer can stand on.")
            continue
        if urgency > out.sell_urgency + 5:
            where = (f"in {out.position}" if len(row) > 4 and row[4] == out.position
                     else f"at {row[4]}" if len(row) > 4 else "in his position")
            lines.append(
                f"{name} scores higher at {urgency:.0f} and is the more "
                f"obvious sale on paper; he is kept because no affordable "
                f"upgrade was found {where} this week.")
        else:
            lines.append(
                f"He is the better sale than {name}, who is {outlook.lower()} "
                f"on {urgency:.0f}/100 — a settled starter with nothing "
                f"published against him is a worse thing to spend a transfer "
                f"removing.")
    if not others:
        lines.append("He is the only realistic sale in the squad this week.")
    return " ".join(lines)


def best_sale_justified(inputs: TransferBriefInputs) -> tuple[bool, str]:
    """Can selling THIS player be justified over the alternatives?

    A hard gate, not a caption. If a more sellable player exists at the
    same position and the outgoing player has nothing against him, the
    engine is selling the wrong man and the move should not stand.
    """
    if not inputs.acting:
        return True, "no sale is being made"
    out, _ = inputs.sides[0]
    if out.injury or not out.secure or out.sell_urgency >= 45:
        return True, f"{out.name} is a genuine problem at {out.sell_urgency:.0f}/100"
    better = [row for row in inputs.other_sales
              if row[0] != out.name and row[1] > out.sell_urgency + 15
              and row[3] not in ("Very likely to start", "Likely to start")
              and (len(row) < 5 or row[4] == out.position)]
    if better:
        return False, (
            f"{better[0][0]} is more sellable ({better[0][1]:.0f} against "
            f"{out.sell_urgency:.0f}) and less secure")
    return True, f"nobody in the squad is a clearer sale than {out.name}"


# --- 5. why THIS player in -----------------------------------------------

def why_in(inputs: TransferBriefInputs) -> str:
    """Why the target beats the realistic alternatives, not the field."""
    if not inputs.acting:
        return ""
    lines = []
    for _, into in inputs.sides:
        line = (f"{into.name} at £{into.price:.1f}m is {into.outlook.lower()} "
                f"({into.minutes_label}), with {into.labels()} to come.")
        if into.penalties:
            line += " He takes the penalties."
        elif into.set_pieces:
            line += " He is on set pieces."
        lines.append(line)

    others = inputs.other_targets[:2]
    for name, delta, why_not in others:
        if why_not:
            lines.append(
                f"{name} was the other option and was refused: "
                f"{_shorten(why_not)}.")
        else:
            lines.append(
                f"{name} models {delta:+.1f} against him over five gameweeks.")
    if not others:
        lines.append(
            "No other affordable target in the position survived the checks, "
            "so this is a choice against the field rather than against a "
            "shortlist.")
    return " ".join(lines)


def _shorten(reason: str) -> str:
    reason = (reason or "").strip().rstrip(".")
    reason = reason.split(": ", 1)[-1]
    for separator in (" — ", " -- "):
        if separator in reason:
            reason = reason.split(separator)[0]
    return reason


# --- 6. why now ----------------------------------------------------------

def why_now(inputs: TransferBriefInputs) -> str:
    """Why this week rather than next — or an admission that there is none.

    Most transfers are not urgent, and pretending otherwise is how a
    manager gets talked into spending a free transfer he would rather
    have kept. Where the urgency is real it is nameable: a fixture run
    that starts now, minutes that are bleeding points every week, an
    unavailable player.
    """
    if not inputs.acting:
        return ("There is nothing to do this week, which is itself the point: "
                "the transfer is worth more next week, when there will be a "
                "team sheet to react to.")

    out, into = inputs.sides[0]
    reasons = []
    if out.injury or out.outlook == "Out":
        reasons.append(
            f"{out.name} is not going to play, so every week he is held costs "
            f"the difference between his zero and a starter's return")
    elif not out.secure:
        reasons.append(
            f"{out.name} is {out.outlook.lower()}, so holding him risks "
            f"another week of bench points rather than a return")
    if into.run(2) + 0.5 < into.run(5):
        reasons.append(
            f"{into.name} begins his good run immediately — {into.labels(2)} "
            f"before it hardens — so waiting spends the best of it")

    if reasons:
        return _prose(reasons)
    return (
        f"There is no urgency. The gain is spread evenly across the run and "
        f"nothing about {out.name} is deteriorating this week, so making this "
        f"next week instead costs almost nothing and buys another round of "
        f"team news. That is an argument for waiting, and it is why the "
        f"verdict below is not a stronger one.")


# --- 7. why not roll -----------------------------------------------------

def why_not_roll(inputs: TransferBriefInputs, label: str = "") -> str:
    """The flexibility being given up, priced against the gain.

    Takes the verdict so the two cannot disagree. Stating "that is enough
    to spend the transfer on" under a verdict of WATCHLIST is the page
    arguing with itself in the space of two sections.
    """
    roll_value = inputs.roll_net
    if not inputs.acting:
        best = _best_rejected(inputs)
        return (
            f"Rolling is stronger because no proposed move improves the squad "
            f"enough to compensate for losing the flexibility of two free "
            f"transfers next week"
            + (f" — the closest, {best}, does not clear it." if best else ".")
            + f" Keeping the transfer is worth about {roll_value:+.1f} on the "
              f"same scale the moves are measured on.")
    plan = inputs.plan
    opening = (
        f"Rolling scores {roll_value:+.1f} on the same scale — the value of "
        f"carrying the transfer as an option on news not yet published. This "
        f"move scores {plan.net_5gw:+.1f} after every cost, a margin of "
        f"{inputs.margin:+.1f}")
    if label and label != MAKE_THE_MOVE:
        return (opening + ". The margin is not the problem here — the move "
                          "fails on the grounds in the verdict below, so "
                          "rolling wins by default rather than on points.")
    if inputs.close_call:
        return (opening + ", which is inside the range where one piece of "
                          "team news could flip it.")
    return opening + ", which is enough to spend the transfer on."


# --- 8. the three-to-five gameweek plan ----------------------------------

def horizon(inputs: TransferBriefInputs) -> str:
    """Where this leaves the squad, and what it forces later."""
    if not inputs.acting:
        return (
            "Next week the squad has two free transfers, which is the only "
            "position from which a two-move package can be made without a "
            "hit. That is the plan: bank the flexibility, and spend it when "
            "there is a team sheet or an injury to spend it on.")

    plan = inputs.plan
    out, into = inputs.sides[0]
    lines = [
        f"{into.name}'s next three: {into.labels(3)} (mean difficulty "
        f"{into.run(3):.1f}). Across five: {into.run(5):.1f}."]
    for _, other in inputs.sides[1:]:
        lines.append(
            f"{other.name}'s: {other.labels(3)} ({other.run(3):.1f}), "
            f"{other.run(5):.1f} across five.")

    if into.run(3) + 0.4 < into.run(5):
        lines.append(
            "The run hardens after the opening fixtures, so this is a "
            "short-term buy that will want revisiting — plan on it costing a "
            "second transfer rather than assuming it will not.")
    elif into.run(5) <= 2.8:
        lines.append(
            "The whole five-gameweek run grades kindly, so he is a hold "
            "rather than a punt and the transfer does not need spending "
            "again.")
    else:
        lines.append(
            "The run holds its level, so nothing here forces a follow-up "
            "move.")

    lines.append(
        f"Afterwards: £{plan.bank_after:.1f}m in the bank and "
        f"{plan.free_transfers_after} free transfer"
        f"{'s' if plan.free_transfers_after != 1 else ''}"
        + (", which funds a bigger move next week."
           if plan.bank_after >= 1.0 else
           ", which is not much room to work with."))
    if plan.reversal_risk >= 1.0:
        lines.append(
            f"Reversal risk is priced at {plan.reversal_risk:.1f} points: "
            f"there is a real chance of wanting {out.name} back.")
    return " ".join(lines)


# --- 9. the package, evaluated as one decision ---------------------------

def package_logic(inputs: TransferBriefInputs) -> str:
    """Two swaps assessed as a pair, because that is what they are.

    A package is not two transfers that happen to be adjacent. It has one
    hit, one bank position and one effect on next week's flexibility, and
    the second move only earns its place if the pair beats the better
    single on its own.
    """
    plan = inputs.plan
    per_move = []
    for move in plan.moves:
        per_move.append(
            f"{move.out_name} → {move.in_name} ({move.position}) "
            f"{move.points_delta:+.1f}")
    return (
        f"Treated as one decision rather than two: {'; '.join(per_move)}. "
        f"Together {plan.gross_5gw:+.1f} gross, "
        f"{('a ' + format(plan.hit, '.0f') + '-point hit') if plan.hit else 'no hit'}, "
        f"{plan.net_5gw:+.1f} net, bank £{plan.bank_before:.1f}m → "
        f"£{plan.bank_after:.1f}m, {plan.free_transfers_after} free transfer"
        f"{'s' if plan.free_transfers_after != 1 else ''} left.")


# --- 10. same-club swaps -------------------------------------------------

def same_club_note(inputs: TransferBriefInputs) -> str:
    """The fixtures are identical, so only the players can separate them."""
    for move in (inputs.plan.moves if inputs.plan else []):
        if not move.same_club:
            continue
        separators = st.differentiating(move.reasons, move)
        money = move.cash_delta
        if separators:
            return (
                f"{move.out_name} and {move.in_name} share every fixture, "
                f"every opponent and the same clean-sheet odds, so the "
                f"fixture run cannot separate them. What does: "
                + "; ".join(reason.text for reason in separators[:2]) + ".")
        if money > 0.2:
            return (
                f"{move.out_name} and {move.in_name} play for the same club, "
                f"so the fixtures are identical and this is not a direct "
                f"upgrade. It is a budget release of £{money:.1f}m, and it is "
                f"only worth doing if that money has somewhere better to go.")
        return (
            f"{move.out_name} and {move.in_name} share every fixture, and "
            f"nothing player-specific separates them. On this evidence the "
            f"swap does not have a reason to exist.")
    return ""


# --- 11. the verdict, which must match the maths -------------------------

def verdict(inputs: TransferBriefInputs) -> tuple[str, str]:
    """A label a manager can act on, and the trade-off behind it.

    Derived from the same net figure the arithmetic line shows, so the
    words and the number cannot disagree — the failure that produced ROLL
    at the top of a page whose next section said make the move.
    """
    if not inputs.acting:
        return ROLL, (
            "Keep the transfer. Nothing available clears the value of "
            "carrying it, and next week it becomes two.")

    plan, (out, into) = inputs.plan, inputs.sides[0]
    if not plan.affordable:
        return NOT_WORTH_A_HIT, (
            f"It cannot be afforded: £{plan.bank_after:.1f}m in the bank "
            f"afterwards. Nothing else about it matters until the money "
            f"works.")
    if plan.hit and inputs.margin < st.DECISION_MARGIN:
        return NOT_WORTH_A_HIT, (
            f"On raw projections the package gains {plan.gross_5gw:+.1f} over "
            f"five gameweeks, but after the {plan.hit:.0f}-point hit the net "
            f"edge is {plan.net_5gw:+.1f} — only {inputs.margin:+.1f} against "
            f"simply rolling. That is not enough to give up a settled pairing "
            f"for.")
    if not into.secure:
        return CONDITIONAL, (
            f"The move is right if {into.name} starts. He is "
            f"{into.outlook.lower()} at {into.minutes_label}, so check the "
            f"team news before committing rather than assuming.")
    if inputs.close_call:
        return HOLD_A_WEEK, (
            f"It edges rolling by {inputs.margin:+.1f}, which is inside the "
            f"noise. Another week of evidence decides it either way, and the "
            f"transfer is not lost by waiting.")
    ok, _ = best_sale_justified(inputs)
    if not ok:
        return WATCHLIST, (
            "The incoming player is right and the outgoing one is not — the "
            "squad has a clearer problem elsewhere, so this is worth "
            "revisiting once that slot is resolved.")
    return MAKE_THE_MOVE, (
        f"{plan.net_5gw:+.1f} over five gameweeks after every cost, against "
        f"{inputs.roll_net:+.1f} for keeping the transfer. Take it.")


def confidence(inputs: TransferBriefInputs) -> str:
    """Never High while the move depends on an unconfirmed starting place."""
    if not inputs.acting:
        return "High"
    plan = inputs.plan
    _, into = inputs.sides[0]
    if not into.secure or into.new_club:
        return "Low" if into.outlook in ("Likely bench", "Very unlikely to start",
                                         "Out") else "Medium"
    if into.confidence == "Low" or plan.confidence == "Low":
        return "Low"
    if inputs.close_call or plan.confidence == "Medium":
        return "Medium"
    return "High"


# --- 12. the trust test, run before anything is published ----------------

def trust_test(inputs: TransferBriefInputs, brief: TransferBrief) -> list:
    """Ten questions. A NO is a stop, not a caveat printed underneath."""
    plan = inputs.plan
    checks = []

    checks.append((
        "Do I understand why THIS player is being sold?",
        bool(brief.why_out) or not inputs.acting,
        brief.why_out[:120] or "no sale is being made"))

    ok, detail = best_sale_justified(inputs)
    checks.append(("Is he the right player to sell?", ok, detail))

    checks.append((
        "Do I understand why THIS player is being bought?",
        bool(brief.why_in) or not inputs.acting,
        brief.why_in[:120] or "no purchase is being made"))

    checks.append((
        "Do I understand why the move is happening now?",
        bool(brief.why_now), brief.why_now[:120]))

    checks.append((
        "Do I understand why rolling is better or worse?",
        bool(brief.why_not_roll), brief.why_not_roll[:120]))

    hit_ok = (not plan or plan.hit == plan.paid_transfers * st.HIT_COST)
    hit_shown = (not plan or not plan.hit
                 or f"{plan.hit:.0f}-point hit" in brief.arithmetic)
    checks.append((
        "Is the hit counted as four real points and stated plainly?",
        hit_ok and hit_shown,
        f"{(plan.paid_transfers if plan else 0)} paid transfer(s) = "
        f"{(plan.hit if plan else 0):.0f} points"))

    money = st.verify_arithmetic(plan) if plan else []
    checks.append(("Does the money add up?", not money,
                   "; ".join(money) or brief.arithmetic[:120]))

    observed = sum(len(st.supports_buying(move)) + len(st.supports_selling(move))
                   for move in (plan.moves if plan else []))
    checks.append((
        "Does the reasoning use actual evidence?",
        observed > 0 or not inputs.acting,
        f"{observed} published item(s) argue for this move"))

    checks.append((
        "Is there a genuine case against it?",
        len(brief.case_against.split()) >= 12, brief.case_against[:120]))

    matches = _verdict_matches(inputs, brief)
    checks.append((
        "Does the verdict match the maths?", matches,
        f"{brief.verdict_label} against net {(plan.net_5gw if plan else 0):+.1f}"))
    return checks


def _verdict_matches(inputs: TransferBriefInputs, brief: TransferBrief) -> bool:
    """The label and the number have to say the same thing."""
    if not inputs.acting:
        return brief.verdict_label == ROLL
    plan = inputs.plan
    if brief.verdict_label == MAKE_THE_MOVE:
        return plan.net_5gw > inputs.roll_net
    if brief.verdict_label == NOT_WORTH_A_HIT:
        return bool(plan.hit)
    return True


# --- assembly ------------------------------------------------------------

def build(inputs: TransferBriefInputs) -> TransferBrief:
    """One transfer, argued end to end."""
    label, rationale = verdict(inputs)
    brief = TransferBrief(
        label=(inputs.plan.label if inputs.plan else "Roll the transfer"),
        arithmetic=arithmetic(inputs),
        why_move=why_move(inputs, label),
        case_for=case_for(inputs),
        case_against=case_against(inputs),
        why_out=why_out(inputs),
        why_in=why_in(inputs),
        why_now=why_now(inputs),
        why_not_roll=why_not_roll(inputs, label),
        horizon=horizon(inputs),
        verdict_label=label,
        verdict=rationale,
        confidence=confidence(inputs),
        evidence=[reason.__dict__ for move in (inputs.plan.moves if inputs.plan else [])
                  for reason in move.reasons][:8],
    )
    note = same_club_note(inputs)
    if note:
        brief.why_in = (brief.why_in + " " + note).strip()
    brief.trust = trust_test(inputs, brief)
    return brief


def rejected_note(plan, out_side: Side = None, in_side: Side = None) -> str:
    """A refused alternative, in two sentences rather than an essay.

    Rejected moves still have to be legible — a reader who wonders why
    the obvious swap is not recommended deserves the reason — but they do
    not deserve the same word count as the decision being made.
    """
    reason = _shorten((plan.rejection_reasons or [""])[0])
    lines = [f"{plan.label} is not recommended: {reason}."]
    if plan.hit:
        lines.append(
            f"It would also cost {plan.hit:.0f} points, against a gross "
            f"{plan.gross_5gw:+.1f}.")
    elif abs(plan.gross_5gw) >= 0.1:
        lines.append(f"On the numbers alone it is {plan.gross_5gw:+.1f} over "
                     f"five gameweeks.")
    return " ".join(lines)


def watchlist_note(plan, trigger_side: Side = None) -> str:
    """A move that is not right yet, with what would make it right.

    Written as a condition rather than a prediction. A future transfer
    stated as a certainty is the same overreach as a starting place
    stated from last season's record.
    """
    reason = _shorten((plan.rejection_reasons or [""])[0])
    triggers = ["he keeps his place and nothing is published against him",
                "the outgoing player remains the weakest slot in that position",
                "the move is still affordable"]
    if trigger_side is not None and not trigger_side.secure:
        triggers.insert(0, f"{trigger_side.name}'s minutes are confirmed")
    return (
        f"WHY WE ARE WAITING: {reason}. "
        f"TRIGGERS: " + "; ".join(triggers) + ". "
        f"Rolling in the meantime builds a second free transfer, which is "
        f"what would let this happen without a hit.")
