"""Loads the weekly odds/expert-sentiment report.

These reports aren't generated by this codebase — direct scraping of
bookmaker and forum sites is blocked from most sandboxed environments and
is against many of those sites' terms anyway. Instead, ask Claude to
"refresh the gameweek report": it runs live web searches for odds and
expert/community takes, synthesises them, and writes the result here as
Markdown. This module just finds and reads that file for the dashboard.
"""
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent.parent / "data" / "reports"


def load_report(gameweek: int) -> tuple[str | None, str | None]:
    """Returns (markdown_text, filename) for the given gameweek, falling back
    to the most recently written report if that exact gameweek isn't there.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    exact = REPORTS_DIR / f"gw{gameweek}.md"
    if exact.exists():
        return exact.read_text(), exact.name

    candidates = sorted(REPORTS_DIR.glob("gw*.md"), key=lambda p: p.stat().st_mtime, reverse=True)
    if candidates:
        return candidates[0].read_text(), candidates[0].name

    return None, None
